# Generated by Django 2.0.7 on 2018-12-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cmpid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cmpname', models.CharField(max_length=20)),
                ('cmptype', models.CharField(max_length=10)),
                ('cmpadd', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=7)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('mobno', models.CharField(max_length=15)),
                ('add', models.CharField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Hr_Data',
            fields=[
                ('hrid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('mobno', models.CharField(max_length=15)),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company')),
            ],
        ),
    ]
