# Generated by Django 2.0.7 on 2018-12-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0005_auto_20181211_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_Login',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('hrid', models.CharField(max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company')),
            ],
        ),
    ]
