# Generated by Django 2.0.7 on 2018-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0007_emp_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_account',
            fields=[
                ('acno', models.IntegerField(primary_key=True, serialize=False)),
                ('bankname', models.CharField(max_length=20)),
                ('ifsccode', models.CharField(max_length=11)),
                ('branchname', models.CharField(max_length=15)),
                ('empid', models.CharField(max_length=7)),
                ('cmpid', models.CharField(max_length=5)),
                ('isactivated', models.BooleanField(default=False)),
            ],
        ),
    ]
