# Generated by Django 2.0.7 on 2018-12-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0008_emp_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_Login',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('acid', models.CharField(max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company')),
            ],
        ),
    ]
