# Generated by Django 2.0.7 on 2018-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0009_finance_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_basic_update',
            fields=[
                ('empid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('basicpay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_Leaves',
            fields=[
                ('empid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('total_no_of_work_days', models.IntegerField(verbose_name=2)),
                ('paid_leaves', models.IntegerField(verbose_name=2)),
                ('non_paid_leaves', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_pal_slip',
            fields=[
                ('empid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('basicpay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('da', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tsal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
