# Generated by Django 2.0.7 on 2018-12-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0010_emp_basic_update_emp_leaves_emp_pal_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_basic_update',
            name='comapny',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
        migrations.AddField(
            model_name='emp_leaves',
            name='comapny',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
        migrations.AddField(
            model_name='emp_pal_slip',
            name='comapny',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
    ]
