# Generated by Django 2.0.7 on 2018-12-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0011_auto_20181224_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_basic_update',
            name='comapny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
        migrations.AlterField(
            model_name='emp_leaves',
            name='comapny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
        migrations.AlterField(
            model_name='emp_pal_slip',
            name='comapny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.Company'),
        ),
    ]
